export const animationOptions = [
    { id: '0', name: 'Default', description: 'Без анимации перехода', type: null },
    { id: '1', name: 'Fade', description: 'Плавный переход от одного кадра к другому', type: 'fade' },
    { id: '2', name: 'Slide Left', description: 'Переход, при котором изображение “стирается” слева направо', type: 'slideleft' },
    { id: '3', name: 'Slide Right', description: 'Переход, при котором изображение “стирается” справа налево', type: 'slideright' },
    { id: '4', name: 'Slide Up', description: 'Переход, при котором изображение “стирается” сверзу вниз', type: 'slideup' },
    // { id: '5', name: 'Slide Down', description: 'Переход, при котором изображение “стирается” снизу вверх', type: 'slidedown' },
    // { id: '6', name: 'Zoom', description: 'Зум-эффект', type: 'zoomin' },
    // { id: '7', name: 'Сircle Сrop', description: 'Переход с обрезкой кадра по кругу', type: 'circlecrop' },
    // { id: '8', name: 'Rect Crop', description: 'Переход с обрезкой кадра по прямоугольнику', type: 'rectcrop' },
    // { id: '9', name: 'Distance', description: 'Переход с эффектом изменения перспективы', type: 'distance' },
    // { id: '10', name: 'Fade Black', description: 'Переход с затемнением в черный', type: 'fadeblack' },
    // { id: '11', name: 'Fade White', description: 'Переход с затемнением в белый', type: 'fade#FFF9F0' },
    // { id: '12', name: 'Radial', description: 'Переход с круговым движением', type: 'radial' },
    // { id: '13', name: 'Smooth Left', description: 'Переход с круговым движением', type: 'smoothleft' },
    // { id: '14', name: 'Smooth Right', description: 'Переход с круговым движением', type: 'smoothright' },
    // { id: '15', name: 'Smooth Up', description: 'Переход с круговым движением', type: 'smoothup' },
    // { id: '16', name: 'Smooth Down', description: 'Переход с круговым движением', type: 'smoothdown' },
    // { id: '17', name: 'Circle Open', description: 'Преход с круговым раскрытием', type: 'circleopen' },
    // { id: '18', name: 'Circle Close', description: 'Переход с круговым закрытием', type: 'circleclose' },
    // { id: '19', name: 'Vert Open', description: 'Переход с вертикальным раскрытием', type: 'vertopen' },
    // { id: '20', name: 'Vert Close', description: 'Переход с вертикальным закрытием', type: 'vertclose' },
    // { id: '21', name: 'Horz Open', description: 'Переход с горизонтальным закрытием', type: 'horzopen' },
    // { id: '22', name: 'Horz Close', description: 'Переход с горизонтальным закрытием', type: 'horzclose' },
    // { id: '23', name: 'Dissolve', description: 'Мягкий переход с наложением кадров', type: 'dissolve' },
    // { id: '24', name: 'Pixelize', description: 'Переход с эффектом пиксельного размытия', type: 'pixelize' },
    // { id: '25', name: 'Diag Tl', description: 'Переход по диагональной линии слева', type: 'diagtl' },
    // { id: '26', name: 'Diag Tr', description: 'Переход по диагональной линии справа', type: 'diagtr' },
    // { id: '27', name: 'Diag Bl', description: 'Переход по диагональной линии сверху', type: 'diagbl' },
    // { id: '28', name: 'Diag Br', description: 'Переход по диагональной линии снизу', type: 'diagbr' },
    // { id: '29', name: 'Hl Slice', description: 'Переход с разрезанием кадра горизонтально', type: 'hlslice' },
    // { id: '30', name: 'Hr Slice', description: 'Переход с разрезанием кадра вертикально', type: 'hrslice' },
    // { id: '31', name: 'Vu Slice', description: 'Переход с разрезанием кадра сверху', type: 'vuslice' },
    // { id: '32', name: 'Vd Slice', description: 'Переход с разрезанием кадра снизу', type: 'vdslice' },
    // { id: '33', name: 'H Blur', description: 'Переход с горизонтальным размытием', type: 'hblur' },
    // { id: '34', name: 'Fade Grays', description: 'Переход с превращением в черно-белое изображение', type: 'fadegrays' },
    // { id: '35', name: 'Wipe Tl', description: 'Переход по диагонали слева', type: 'wipetl' },
    // { id: '36', name: 'Wipe Tr', description: 'Переход по диагонали справа', type: 'wipetr' },
    // { id: '37', name: 'Wipe Bl', description: 'Переход по диагонали сверху', type: 'wipebl' },
    // { id: '38', name: 'Wipe Br', description: 'Переход по диагонали снизу', type: 'wipebr' },
    // { id: '39', name: 'Squeeze H', description: 'Переход со сжатием по горизонтали', type: 'squeezeh' },
    // { id: '40', name: 'Squeeze V', description: 'Переход со сжатием по вертикали', type: 'squeezev' },
    // { id: '41', name: 'Zoom In', description: 'Переход с приближением', type: 'zoomin' },
    // { id: '42', name: 'Fade Fast', description: 'Быстрый переход с затуханием', type: 'fadefast' },
    // { id: '43', name: 'Fade Slow', description: 'Медленный переход с затуханием', type: 'fadeslow' },
];